[package]
name = "rs2048"
version = "0.1.0"
authors = ["Mathias Rav <m@git.strova.dk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "*"
